theme = "fleet_dark"

[editor]
middle-click-paste = false
line-number = "absolute"
mouse = true
true-color = true
idle-timeout = 0
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
