theme = "gruvbox_dark_hard"

[editor]
middle-click-paste = false
line-number = "absolute"
mouse = true
true-color = true
idle-timeout = 0
bufferline = "always"
auto-completion = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

