
If:
  PathMatch: '.*\.cpp'
  PathMatch: '.*\.hpp'
  PathMatch: '.*\.mpp'
  PathMatch: '.*\.cppm'
CompileFlags:
  Add: ["-stdlib=libc++"]
  Add: ["-std=c++23"]
  Add: ["-Wall", "-Wextra"]
  Add: ["-Wl,-rpath,/usr/lib"]
  Add: ["-fmodule-search-path"]
  Add: ["-fmodules"]
  Compiler: clang++
# Diagnostics:
#   ClangTidy:
#     Add: ['modernize-*', 'readability-*']
#     Remove: modernize-use-trailing-return-type

