
If:
  PathMatch: '.*\.cpp'
  PathMatch: '.*\.hpp'
CompileFlags:
  # Add: ["-std=c++23", "-Weverything", "-stdlib=libc++", "-Wl,-rpath,/usr/lib"]
  Add: ["-Wall", "-Wextra"]
  # Add: ["-Weverything"]
  Compiler: clang++
# Diagnostics:
  # ClangTidy:
    # Add: ['modernize-*', 'readability-*']
